name: Update README with recent activity

on:
  schedule:
    - cron: '0 * * * *'  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JamesIves/github-activity-readme@v0.4.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
